# Generated by Django 5.1 on 2024-09-07 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_initial'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(error_messages={'blank': 'The owner user must be specified', 'null': 'The owner user must be specified'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='languages',
            field=models.ManyToManyField(limit_choices_to={'category': 'L'}, related_name='post_set_languages', to='app.skill'),
        ),
        migrations.AddField(
            model_name='post',
            name='technologies',
            field=models.ManyToManyField(limit_choices_to={'category': 'T'}, related_name='post_set_technologies', to='app.skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(help_text='Choose your best skills', to='app.skill'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.ForeignKey(error_messages={'blank': 'You must specify a programming language', 'null': 'You must specify a programming language'}, help_text='Choose the programming language used', limit_choices_to={'category': 'L'}, on_delete=django.db.models.deletion.PROTECT, related_name='snippet_set_language', to='app.skill'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='technology',
            field=models.ManyToManyField(help_text='Choose the programming technology used', limit_choices_to={'category': 'T'}, related_name='snippet_set_technology', to='app.skill'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.ManyToManyField(error_messages={'blank': 'You need to add one snippet at least', 'null': 'You need to add one snippet at least'}, help_text='Code to be posted', to='app.snippet'),
        ),
    ]
