# Generated by Django 5.1 on 2024-09-08 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_user_avatar_alter_user_complete_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Choose your best skills', to='app.skill'),
        ),
    ]
