# Generated by Django 5.1 on 2024-09-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_friends_list_alter_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='technology',
            field=models.ManyToManyField(blank=True, help_text='Choose the programming technology used', limit_choices_to={'category': 'T'}, related_name='snippet_set_technology', to='app.skill'),
        ),
    ]
