# Generated by Django 5.1 on 2024-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_snippet_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, error_messages={'max_length': 'Your description is too long'}, help_text='Description of your post', max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippets',
            field=models.ManyToManyField(error_messages={'blank': 'You need to add one snippet at least'}, help_text='Code to be posted', to='app.snippet'),
        ),
    ]
