# Generated by Django 5.1 on 2024-09-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_post_description_alter_post_snippets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='technologies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'category': 'T'}, related_name='post_set_technologies', to='app.skill'),
        ),
    ]
