# Generated by Django 5.1 on 2024-09-08 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_post_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(error_messages={'blank': "The post of the comment can't be empty", 'null': "The post of the comment can't be empty"}, help_text='The post of the comment', on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(error_messages={'blank': "The owner of the comment can't be empty", 'null': "The owner of the comment can't be empty"}, help_text='The owner of the comment', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='languages',
            field=models.ManyToManyField(error_messages={'blank': 'At least one programming language need to be specified'}, help_text='The programming languages used in the post', limit_choices_to={'category': 'L'}, related_name='post_set_languages', to='app.skill'),
        ),
        migrations.AlterField(
            model_name='post',
            name='share_url',
            field=models.URLField(error_messages={'blank': 'The post need a url for sharing', 'null': 'The post need a url for sharing'}, help_text='The post url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='technologies',
            field=models.ManyToManyField(blank=True, help_text='The technologies used in the post', limit_choices_to={'category': 'T'}, related_name='post_set_technologies', to='app.skill'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(error_messages={'blank': 'The owner user must be specified', 'null': 'The owner user must be specified'}, help_text='The owner of the post', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('L', 'Language'), ('T', 'Technology')], error_messages={'blank': "The category can't be empty", 'null': "The category can't be empty"}, help_text='Choose if is a lenguage or technology', max_length=50),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='user',
            field=models.ForeignKey(error_messages={'blank': 'The owner need to be specified', 'null': 'The owner need to be specified'}, help_text='The snippet owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday_date',
            field=models.DateField(blank=True, help_text='Define your birthday', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='complete_name',
            field=models.CharField(blank=True, error_messages={'max_length': 'This name is too long'}, help_text='The complete name', max_length=100, null=True),
        ),
    ]
