# Generated by Django 5.1 on 2024-09-16 19:38

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_comment_post_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', help_text='Upload an image that represent you', null=True, upload_to=app.models.User.user_directory_path),
        ),
    ]
