# Generated by Django 5.1 on 2024-09-16 20:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload an image that represent you', null=True, upload_to=app.models.User.user_directory_path),
        ),
    ]
