# Generated by Django 5.1 on 2024-09-17 20:44

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=app.models.User.default_avatar_selection, help_text='Upload an image that represent you', upload_to=app.models.User.user_directory_path),
        ),
    ]
