# Generated by Django 5.1 on 2024-09-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, default='', help_text='Choose your best skills', null=True),
        ),
    ]
