# Generated by Django 5.1 on 2024-09-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_user_skills_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(error_messages={'blank': "Your snippet can't be empty", 'max_length': 'Your snippet is too long', 'null': "Your snippet can't be empty"}, help_text='Write your snippet here', max_length=90000),
        ),
    ]
