# Generated by Django 5.1 on 2024-09-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_snippet_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.ForeignKey(error_messages={'blank': 'You must specify a programming language', 'null': 'You must specify a programming language'}, help_text='Choose the programming language used', limit_choices_to={'category': 'L'}, on_delete=django.db.models.deletion.CASCADE, related_name='snippet_set_language', to='app.skill'),
        ),
    ]
