# Generated by Django 5.1 on 2024-09-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_snippet_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='language_name',
            field=models.CharField(blank=True, error_messages={'blank': "The name can't be empty", 'max_length': 'Name is too long', 'null': "The name can't be empty"}, help_text='Name of the programming language used in the snippet', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='technology_names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
