# Generated by Django 5.1 on 2024-09-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_snippet_language_name_snippet_technology_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='technology_names',
            field=models.JSONField(blank=True, max_length=200, null=True),
        ),
    ]
