# Generated by Django 5.1 on 2024-09-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_snippet_technology_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language_name',
            field=models.JSONField(blank=True, max_length=50, null=True),
        ),
    ]
