# Generated by Django 5.1 on 2024-10-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_snippet_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.JSONField(default=dict),
        ),
    ]
