# Generated by Django 5.1 on 2024-10-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_post_description_post_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='share_url',
            field=models.CharField(error_messages={'blank': 'The post need a url for sharing', 'null': 'The post need a url for sharing'}, help_text='The post url'),
        ),
    ]
