# Generated by Django 5.1 on 2024-10-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_post_share_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='languages_names',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='technologies_names',
            field=models.JSONField(blank=True, max_length=800, null=True),
        ),
    ]
