# Generated by Django 5.1 on 2024-10-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_post_languages_names_post_technologies_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job_position',
            field=models.CharField(blank=True, error_messages={'max_length': 'This name is too long'}, help_text='The job position in your current company', max_length=100, null=True),
        ),
    ]
