# Generated by Django 5.1 on 2024-10-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_user_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='languages',
            field=models.ManyToManyField(blank=True, error_messages={'blank': 'At least one programming language need to be specified'}, help_text='The programming languages used in the post', limit_choices_to={'category': 'L'}, related_name='post_set_languages', to='app.skill'),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippets',
            field=models.ManyToManyField(blank=True, error_messages={'blank': 'You need to add one snippet at least'}, help_text='Code to be posted', to='app.snippet'),
        ),
    ]
