# Generated by Django 5.1 on 2024-10-11 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_post_languages_alter_post_snippets'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_who_vote_down',
            field=models.ManyToManyField(blank=True, related_name='users_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='users_who_vote_up',
            field=models.ManyToManyField(blank=True, related_name='users_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
