# Generated by Django 5.1 on 2024-10-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_post_users_who_vote_down_post_users_who_vote_up'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvotes_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='snippets_count',
        ),
    ]
