# Generated by Django 5.1 on 2024-10-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_post_downvotes_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posts_ups_count',
            field=models.SmallIntegerField(default=0),
        ),
    ]
