# Generated by Django 5.1 on 2024-10-18 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_comment_downvotes_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.AddField(
            model_name='post',
            name='users_who_comment',
            field=models.ManyToManyField(blank=True, related_name='commented_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
