# Generated by Django 5.1 on 2024-10-18 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_post_comments_count_post_users_who_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='responses',
            field=models.ManyToManyField(blank=True, to='app.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, error_messages={'blank': "The post of the comment can't be empty", 'null': "The post of the comment can't be empty"}, help_text='The post of the comment', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
    ]
