# Generated by Django 5.1 on 2024-10-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_comment_responses_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_who_comment',
        ),
        migrations.AddField(
            model_name='post',
            name='users_who_comment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
