# Generated by Django 5.1 on 2024-10-23 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_post_users_who_comment_post_users_who_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(error_messages={'blank': "This field can't be blank", 'null': "This field can't be null"}, help_text='The notification message', max_length=200)),
                ('url', models.CharField(error_messages={'blank': "This field can't be blank", 'null': "This field can't be null"}, help_text='Relative url to the notification action', max_length=500)),
                ('from_user', models.ForeignKey(error_messages={'blank': "This field can't be blank", 'null': "This field can't be null"}, help_text='User who will generate the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notification_from_user_set', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(error_messages={'blank': "This field can't be blank", 'null': "This field can't be null"}, help_text='User who will generate the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notification_to_user_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
