# Generated by Django 5.1 on 2024-10-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='saw',
            field=models.BooleanField(default=False),
        ),
    ]
