# Generated by Django 5.1 on 2024-10-24 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_notification_saw'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='saw',
            new_name='viewed',
        ),
    ]
