# Generated by Django 5.1 on 2024-10-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_saw_notification_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.CharField(blank=True, error_messages={'blank': "Your description can't be empty", 'max_length': 'Your description is too long', 'null': "Your description can't be empty"}, help_text='Your snippet description', max_length=100, null=True),
        ),
    ]
